version: "3"
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    labels:
      description: "Web server"
      environment: "production"
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  redis:
    image: redis
    labels:
      description: "Redis cache"
      environment: "production"

networks:
  default:
    labels:
      network: "frontend"

volumes:
  mydata:
    labels:
      volume: "database"
