name: Deploy in OCI

on:
  push:
    branches:
      - main
    #paths:
    #  - "docker-compose/*.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          path: docker-compose

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Copy Docker Compose File via SSH
        run: scp ${{ steps.changed-files.outputs.all_changed_files }} ${{ vars.OCI_USER }}@${{ vars.OCI_SERVER}}:~/

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ vars.OCI_USER }}@${{ vars.OCI_SERVER }} "
            docker-compose -f ${{ matrix.compose_file }} down &&
            docker-compose -f ${{ matrix.compose_file }} up -d
          "
